import type React from 'react'

export const ui = {
  color: {
    appBg: '#0e1011',
    panel: '#1a1b1e',
    panelSubtle: '#18191c',
    panelRaised: '#1e2022',
    input: '#141517',
    badge: '#191a1d',
    control: '#242528',
    controlHover: '#2e2f33',
    border: '#2a2b2e',
    text: '#c9cdd1',
    textStrong: '#e2e4e6',
    textMuted: '#6b7280',
    textDim: '#4a4b4e',
    textFaint: '#3a3b3e',
    accent: '#4ade80',
    danger: '#f87171',
  },
  radius: {
    xs: 2,
    sm: 3,
    md: 5,
    lg: 6,
    modal: 10,
  },
  shadow: {
    menu: '0 8px 24px rgba(0,0,0,0.55)',
    overlay: '0 24px 64px rgba(0,0,0,0.6)',
  },
  z: {
    resizeHandle: 10,
    menuBackdrop: 200,
    menu: 201,
  },
  chrome: {
    height: 42,
    detachedHeight: 34,
    background: '#111315',
    backgroundDetached: '#121416',
    tabActive: '#1e2022',
    tabInactiveHover: '#1a1b1e',
    controlSize: 32,
    windowControlWidth: 46,
  },
  className: {
    darkScrollbar: 'dark-scrollbar',
  },
} as const

export const border = {
  default: `1px solid ${ui.color.border}`,
  accent: `1px solid ${ui.color.accent}`,
} as const

export const sidebarStyles = {
  root: {
    backgroundColor: ui.color.panel,
    borderRight: border.default,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    flexShrink: 0,
    position: 'relative',
  },
  actionRow: {
    padding: '8px 8px 6px',
    display: 'flex',
    gap: 5,
  },
  scrollArea: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    width: '100%',
    padding: '6px 12px',
    color: ui.color.textMuted,
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    userSelect: 'none',
    boxSizing: 'border-box',
  },
  sectionTitleButton: {
    background: 'none',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    color: 'inherit',
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    flex: 1,
    textAlign: 'left',
  },
  sectionToggle: {
    background: 'none',
    border: 'none',
    padding: 0,
    color: 'inherit',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
  },
  sectionCount: {
    marginLeft: 'auto',
    fontSize: 11,
    color: ui.color.textDim,
    fontWeight: 400,
    textTransform: 'none',
    letterSpacing: 0,
    flexShrink: 0,
  },
  hoverActionGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    flexShrink: 0,
    transition: 'opacity 0.1s',
  },
  hoverIconButton: {
    width: 18,
    height: 18,
    border: 'none',
    borderRadius: ui.radius.sm,
    background: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    cursor: 'pointer',
    flexShrink: 0,
  },
  hoverIconImage: {
    width: 12,
    height: 12,
    display: 'block',
    opacity: 0.72,
  },
  paneHoverActionGroup: {
    position: 'absolute',
    right: 7,
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    transition: 'opacity 0.1s',
  },
  dock: {
    flexShrink: 0,
    borderTop: border.default,
    backgroundColor: ui.color.panelSubtle,
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
  },
  resizeHandleVertical: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 4,
    cursor: 'col-resize',
    zIndex: ui.z.resizeHandle,
  },
  resizeHandleHorizontal: {
    position: 'absolute',
    top: -3,
    left: 0,
    right: 0,
    height: 6,
    cursor: 'row-resize',
    zIndex: ui.z.resizeHandle + 1,
  },
} satisfies Record<string, React.CSSProperties>

export const menuStyles = {
  backdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: ui.z.menuBackdrop,
  },
  panel: {
    position: 'fixed',
    zIndex: ui.z.menu,
    backgroundColor: ui.color.panel,
    border: border.default,
    borderRadius: ui.radius.lg,
    padding: '4px 0',
    minWidth: 200,
    boxShadow: ui.shadow.menu,
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '7px 12px',
    background: 'none',
    border: 'none',
    textAlign: 'left',
    fontSize: 12,
    gap: 12,
  },
  label: {
    padding: '5px 12px 3px',
    fontSize: 10,
    color: ui.color.textDim,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  separator: {
    height: 1,
    backgroundColor: ui.color.border,
    margin: '3px 0',
  },
} satisfies Record<string, React.CSSProperties>

export const controlStyles = {
  sidebarButton: {
    padding: '5px 4px',
    backgroundColor: ui.color.control,
    border: border.default,
    borderRadius: ui.radius.md,
    color: ui.color.text,
    fontSize: 11,
    cursor: 'pointer',
    fontWeight: 500,
    textAlign: 'center',
  },
} satisfies Record<string, React.CSSProperties>
